---
http:
  routers:
    to-api:
      rule: "Host(`api.traefik.khulnasoft.com`) && PathPrefix(`/`)"
      service: api

    to-secure-api:
      rule: "Host(`api.traefik.khulnasoft.pvt`) && PathPrefix(`/`)"
      service: api
      tls: {}

    to-secure-grpc:
      rule: "Host(`grpc.traefik.khulnasoft.pvt`)"
      service: grpc
      tls: {}

  services:
    api:
      loadBalancer:
        servers:
          - url: http://api.khulnasoft.pvt:8080

    grpc:
      loadBalancer:
        servers:
          - url: h2c://api.khulnasoft.pvt:8082

tls:
  options:
    default:
      maxVersion: VersionTLS13
  certificates:
    - certFile: /etc/ssl/certs/traefik-khulnasoft-pvt.pem
      keyFile: /etc/ssl/private/traefik-khulnasoft-pvt-key.pem
